version: "3.9"
   
services:
  store:
    build:
      context: store 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./store:/code
    ports:
      - "8000:8000"
  warehouse:
    build:
      context: warehouse 
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./warehouse:/code
    ports:
      - "9000:9000"
